'''Create a program that will play the “cows and bulls” game with the user. The game works like this:

Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. For every digit that the user guessed
 correctly in the correct place, they have a “cow”. For every digit the user guessed correctly in the wrong place
 is a “bull.” Every time the user makes a guess, tell them how many “cows” and “bulls” they have. Once the user
 guesses the correct number, the game is over. Keep track of the number of guesses the user makes throughout the
 game and tell the user at the end.

Say the number generated by the computer is 1038. An example interaction could look like this:

  Welcome to the Cows and Bulls Game!
  Enter a number:
  >>> 1234
  2 cows, 0 bulls
  >>> 1256
  1 cow, 1 bull
  ...

Until the user guesses the number.'''

import random

a = 0
guesses = 0
gene = random.randint(1000, 9999)
gene = str(gene)

while a == 0:

    print(gene)
    userGuess = input("Guess a 4 digit number, we are going to play cows and bulls! ")
    userGuess = str(userGuess)
    guesses += 1
    cows = 0
    bulls = 0

    for x in range(0, 4):
        if userGuess[x] == gene[x]:
            cows += 1
    for x in range(0, 4):
        for y in range(0, 4):
            if x != y and userGuess[x] == gene[y]:
                bulls += 1

    if cows == 4:
        print("Congratulations your guess was the correct number of %s, it took you %s guesses as well" % (gene, guesses))
        a = 1
    else:
        print("You have %s bulls and %s cows with your guess of %s" % (bulls, cows, userGuess))
